# syntax=docker/dockerfile:1

##
## Build
##
FROM golang:1.19-buster AS build

WORKDIR /app

COPY src/go.mod ./
COPY src/go.sum ./
RUN go mod download

COPY src ./


RUN go build -o /application

##
## Deploy
##
FROM gcr.io/distroless/base-debian11
ARG version
ARG serviceName
ARG buildTime
ENV SERVICE_VERSION=${version}
ENV SERVICE_NAME=${serviceName}
ENV SERVICE_BUILD_TIME=${buildTime}
WORKDIR /

COPY --from=build /application /application
COPY --from=build /app/data.json /data.json

EXPOSE 8080

USER nonroot:nonroot

ENV GIN_MODE=release

ENTRYPOINT ["/application"]
