apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: {{ gitops_instance_name }}
  namespace: {{ gitops_instance_namespace }}
spec:
  ha:
    enabled: {{ gitops_instance_high_availability }}
  repo:
    replicas: 1
  server:
    replicas: 1
    # Configure TLS edge-terminated route instead of passthrough
    insecure: true
  # Enable Helm templating in Kustomize
  kustomizeBuildOptions: --enable-helm
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, cluster-admins, role:admin
    scopes: '[groups]'
  notifications:
    enabled: false
  extraConfig:
    repositories: |
      - type: helm
        url: https://external-secrets.github.io/kubernetes-external-secrets
        name: external-secrets
