service:
  name: film-api
  image: quay.io/dborrego/film-api
  versions: 
    - tag: no-default-value
      weight: no-default-value

deployment:
  replicas: 2
  port: 8080
  health:
    liveness: /api/v1/health
    readiness: /api/v1/health
  resources: 
    limits:
      cpu: 250m
      memory: 32Mi
    requests:
      cpu: 100m
      memory: 8Mi

config:
  env:
    - name: FILM_SERVICE_URL
      value: http://film-storage.dev-legacy.svc.cluster.local/api/v1/film
    - name: USER_SERVICE_URL
      value: http://user-storage.dev-legacy.svc.cluster.local/api/v1/user/
    - name: COMMENT_SERVICE_URL
      value: comment-service.dev-media.svc.cluster.local:80
