apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kiali-ossm
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kiali-ossm
  source: redhat-operator-index
  sourceNamespace: openshift-marketplace
  startingCSV: kiali-operator.v1.57.5
