apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  destination:
    namespace: mongodb
    server: https://kubernetes.default.svc
  project: bbdd
  source:
    path: resources/mongodb
    repoURL: https://github.com/dbgjerez/service-mesh-workshop
    targetRevision: develop
  syncPolicy:
    automated: {}