apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.service.name }}
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/dev-gateway
  http:
  - match:
    - uri:
        prefix: /api/v1/users
    route:
    - destination:
        host: {{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local