apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: operators
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'argocd'
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - 'https://github.com/dbgjerez/ta.git'