service:
  name: film-frontend
  image: b0rr3g0/film-frontend
  version: 0.1.9

deployment:
  replicas: 1
  port: 80
  health:
    liveness: /
    readiness: /

config:
  env:
    - name: SERVICE_NAME
      value: film-frontend
    - name: SERVICE_VERSION
      value: 0.1.9