apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.service.name }}
spec:
  hosts: 
  - {{ .Values.service.name }}
  gateways:
  - istio-system/dev-gateway
  http:
  - route:
    - destination:
        host: {{ .Values.service.name }}