apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-mesh
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: service-mesh
  source:
    path: components/openshift/rhsm
    repoURL: https://github.com/dbgjerez/service-mesh-workshop
    targetRevision: feature/ocp
  syncPolicy:
    automated: {}