apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: components/openshift/argocd
    repoURL: https://github.com/dbgjerez/service-mesh-workshop
    targetRevision: feature/ocp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true