apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: operators
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'istio-system'
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - 'https://github.com/dbgjerez/service-mesh-workshop'