apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rhsm
  namespace: istio-system
spec:
  to:
    kind: Service
    name: istio-ingressgateway
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: http2