gitops_subscription_namespace: openshift-operators
gitops_subscription_name: openshift-gitops
gitops_subscription_channel: latest
gitops_subscription_approval: Automatic

gitops_instance_namespace: openshift-gitops
gitops_instance_name: openshift-gitops

gitops_instance_high_availability: false

generic_user_password: ChangeMe22