apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: films
spec:
  selector:
    # TODO: ingress to bootstrap with the istio provisioning
    istio: dev-istio-ingress # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"