- name: Configure Argo CD
  kubernetes.core.k8s:
    template:
      - openshift-gitops-cluster-secret.yaml
      - openshift-gitops-argocd-default.yaml
      - gitops-cluster-admin-clusterrolebinding.yaml