- name: Obtain Argo CD route
  kubernetes.core.k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: '{{ gitops_instance_name }}-server'
    namespace: '{{ gitops_instance_namespace }}'
  register: argocd_route
  
- name: Waiting since {{ lookup("pipe", "date +%r") }} for Argo CD to come up
  uri:
    url: 'https://{{ argocd_route.resources.0.spec.host }}/api/v1/session'
    method: POST
    body:
      username: admin
      password: '{{ generic_user_password }}'
    body_format: json
    validate_certs: false
  register: result
  until: result.status == 200
  retries: 60
  delay: 10

- name: Report success
  set_fact:
    msg: |
      Argo CD installed successfully.

      You can browse to https://{{ argocd_route.resources.0.spec.host }}

      Or you can log in with 'argocd login --insecure {{ argocd_route.resources.0.spec.host }} --username admin'

- debug: msg="{{ msg.split('\n') }}"
